#ifndef PLV_ADVANCEDTRACKING_PLUGIN_GLOBAL_H
#define PLV_ADVANCEDTRACKING_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QDebug>

#if defined(PLV_ADVANCEDTRACKING_PLUGIN_LIBRARY)
#  define PLV_ADVANCEDTRACKING_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLV_ADVANCEDTRACKING_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif 
