#ifndef PLV_SYNCHRONY_PLUGIN_GLOBAL_H
#define PLV_SYNCHRONY_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QDebug>

#if defined(PLV_SYNCHRONY_PLUGIN_LIBRARY)
#  define PLV_SYNCHRONY_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLV_SYNCHRONY_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HELLO_WORLD_PLUGIN_GLOBAL_H
